import type { Goal, TimerCategory } from "./types";

export const TIMER_CATEGORIES: TimerCategory[] = [
  {
    id: "skillbox-1c",
    name: "1С Skillbox",
    group: "profession",
    description: "Учебные блоки, конспекты, задачи и разборы Skillbox.",
  },
  {
    id: "practice-final",
    name: "Практика / финальная работа",
    group: "profession",
    description: "Практические задания и сдача финальной работы.",
  },
  {
    id: "pet-construction",
    name: "Пет-проект Строительная бригада",
    group: "profession",
    description: "Функции, архитектура, интерфейсы и демонстрация проекта.",
  },
  {
    id: "interview-questions",
    name: "Вопросы к собеседованию",
    group: "profession",
    description: "Теория, карточки, ответы вслух и повторение.",
  },
  {
    id: "livecoding-1c",
    name: "Лайвкодинг 1С",
    group: "profession",
    description: "Решение задач руками в ограниченное время.",
  },
  {
    id: "resume-market",
    name: "Резюме / HR / рынок",
    group: "profession",
    description: "Резюме, отклики, вакансии, HR-переписка и рынок.",
  },
  {
    id: "current-job",
    name: "Текущая работа",
    group: "work",
    description: "Время, которое забирает текущая работа.",
  },
  {
    id: "gym",
    name: "Зал",
    group: "body",
    description: "Силовая тренировка или полноценная работа в зале.",
  },
  {
    id: "walking",
    name: "Ходьба",
    group: "body",
    description: "Шаги, прогулки, целевая активность.",
  },
  {
    id: "bike",
    name: "Велосипед",
    group: "body",
    description: "Велотренировка или поездки как активность.",
  },
  {
    id: "stretching",
    name: "Растяжка / восстановление",
    group: "body",
    description: "Мобилити, растяжка, восстановление, легкая активность.",
  },
  {
    id: "household",
    name: "Бытовые дела",
    group: "other",
    description: "Дом, документы, бытовые задачи.",
  },
  {
    id: "rest",
    name: "Отдых",
    group: "other",
    description: "Осознанный отдых без маскировки прокрастинации.",
  },
];

export const GROUP_LABELS = {
  profession: "Профессия",
  body: "Тело",
  work: "Работа",
  other: "Прочее",
} as const;

export const DEFAULT_GOALS: Omit<Goal, "userId" | "createdAt" | "updatedAt">[] = [
  {
    id: "goal-skillbox-module-2",
    title: "Закрыть второй модуль Skillbox",
    type: "profession",
    targetValue: 100,
    currentValue: 0,
    deadline: "",
    status: "active",
  },
  {
    id: "goal-final-module-2",
    title: "Сдать финальную работу второго модуля",
    type: "profession",
    targetValue: 1,
    currentValue: 0,
    deadline: "",
    status: "active",
  },
  {
    id: "goal-certificate",
    title: "Получить сертификат",
    type: "profession",
    targetValue: 1,
    currentValue: 0,
    deadline: "",
    status: "active",
  },
  {
    id: "goal-module-3",
    title: "Пройти третий модуль",
    type: "profession",
    targetValue: 100,
    currentValue: 0,
    deadline: "",
    status: "active",
  },
  {
    id: "goal-pet-project",
    title: "Начать пет-проект Строительная бригада",
    type: "profession",
    targetValue: 1,
    currentValue: 0,
    deadline: "",
    status: "active",
  },
  {
    id: "goal-150-questions",
    title: "Разобрать 150 вопросов к собеседованию",
    type: "profession",
    targetValue: 150,
    currentValue: 0,
    deadline: "",
    status: "active",
  },
  {
    id: "goal-100-responses",
    title: "Отправить 100 откликов",
    type: "market",
    targetValue: 100,
    currentValue: 0,
    deadline: "",
    status: "active",
  },
  {
    id: "goal-10-interviews",
    title: "Пройти 10 собеседований",
    type: "market",
    targetValue: 10,
    currentValue: 0,
    deadline: "",
    status: "active",
  },
  {
    id: "goal-offer",
    title: "Получить оффер",
    type: "market",
    targetValue: 1,
    currentValue: 0,
    deadline: "",
    status: "active",
  },
  {
    id: "goal-clean-food-14",
    title: "14 чистых дней питания",
    type: "body",
    targetValue: 14,
    currentValue: 0,
    deadline: "",
    status: "active",
  },
  {
    id: "goal-no-alcohol-60",
    title: "60 дней без алкоголя",
    type: "body",
    targetValue: 60,
    currentValue: 0,
    deadline: "",
    status: "active",
  },
  {
    id: "goal-weight-67",
    title: "Вес 67 кг",
    type: "body",
    targetValue: 67,
    currentValue: 0,
    deadline: "",
    status: "active",
  },
  {
    id: "goal-weight-65",
    title: "Вес 65 кг",
    type: "body",
    targetValue: 65,
    currentValue: 0,
    deadline: "",
    status: "active",
  },
  {
    id: "goal-3-workouts-week",
    title: "3 тренировки в неделю",
    type: "body",
    targetValue: 3,
    currentValue: 0,
    deadline: "",
    status: "active",
  },
  {
    id: "goal-activity-550-700",
    title: "Активность 550-700 ккал в день",
    type: "body",
    targetValue: 700,
    currentValue: 0,
    deadline: "",
    status: "active",
  },
];

export const TARGETS = {
  dailyProfessionMinutes: 240,
  dailyBodyMinutes: 60,
  weeklyOneCMinutes: 600,
  weeklyPracticeMinutes: 300,
  weeklyPetProjectMinutes: 240,
  weeklyBodyMinutes: 300,
};
